services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"

  discovery-server:
    container_name: "eureka"
    build:
      context: discover-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - inter-nodes

  gateway:
    container_name: "gateway"
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - inter-nodes
    depends_on:
      - discovery-server


  client-service:
    build:
      context: client-service
      dockerfile: Dockerfile
    ports:
      - "8100-8199:8100"
    networks:
      - inter-nodes
    deploy:
      replicas: 1
    depends_on:
      - discovery-server
      - gateway
      - rabbitmq

  user-service:
    container_name: "user-service"
    build:
      context: user-service
      dockerfile: Dockerfile
    ports:
      - "8000-8099:8000"
    networks:
      - inter-nodes
    deploy:
      replicas: 1
    depends_on:
      - discovery-server
      - gateway
      - rabbitmq

  external-servers:
    build:
      context: external-servers
      dockerfile: Dockerfile
    ports:
      - "3000-3099:3000"
    deploy:
      replicas: 1
    networks:
      - inter-nodes
networks:
  inter-nodes:
    driver: bridge