services:
  discovery-server:
    container_name: "eureka"
    build:
      context: discover-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - inter-nodes

  client-service:
    build:
      context: client-service
      dockerfile: Dockerfile
    ports:
      - "8100-8199:8100"
    networks:
      - inter-nodes
    deploy:
      replicas: 3

  user-service:
    container_name: "user-service"
    build:
      context: user-service
      dockerfile: Dockerfile
    ports:
      - "8000-8099:8000"
    networks:
      - inter-nodes
    deploy:
      replicas: 1

  gateway:
    container_name: "gateway"
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - inter-nodes

networks:
  inter-nodes:
    driver: bridge